import 'package:intl/intl.dart';

class AppLocalizations {
  static const Map<String, Map<String, String>> _localizedStrings = {
    'en': {
      'app_title': 'Iraq Job Monitor',
      'home': 'Home',
      'jobs': 'Jobs',
      'keywords': 'Keywords',
      'groups': 'Groups',
      'settings': 'Settings',
      'favorites': 'Favorites',
      'search': 'Search',
      'filter': 'Filter',
      'sort': 'Sort',
      'add': 'Add',
      'delete': 'Delete',
      'edit': 'Edit',
      'save': 'Save',
      'cancel': 'Cancel',
      'yes': 'Yes',
      'no': 'No',
      'loading': 'Loading...',
      'error': 'Error',
      'success': 'Success',
      'todayJobs': 'Today\'s Jobs',
      'relevantJobs': 'Relevant Jobs',
      'monitoredGroups': 'Monitored Groups',
      'totalKeywords': 'Total Keywords',
      'monitoringStatus': 'Monitoring Status',
      'lastSync': 'Last Sync',
      'company': 'Company',
      'title': 'Title',
      'location': 'Location',
      'date': 'Date',
      'source': 'Source',
      'importance': 'Importance',
      'share': 'Share',
      'addFavorite': 'Add to Favorites',
      'removeFavorite': 'Remove from Favorites',
      'darkMode': 'Dark Mode',
      'language': 'Language',
      'notifications': 'Notifications',
      'backgroundMonitoring': 'Background Monitoring',
      'autoUpdate': 'Auto Update',
      'exportDatabase': 'Export Database',
      'importDatabase': 'Import Database',
      'backup': 'Backup',
      'restore': 'Restore',
      'logout': 'Logout',
      'login': 'Login',
      'connecting': 'Connecting to Telegram...',
      'enterPhoneNumber': 'Enter your phone number',
      'enterCode': 'Enter verification code',
      'enterPassword': 'Enter your password',
    },
    'ar': {
      'app_title': 'مراقب الوظائف العراقية',
      'home': 'الرئيسية',
      'jobs': 'الوظائف',
      'keywords': 'الكلمات المفتاحية',
      'groups': 'المجموعات',
      'settings': 'الإعدادات',
      'favorites': 'المفضلة',
      'search': 'بحث',
      'filter': 'تصفية',
      'sort': 'ترتيب',
      'add': 'إضافة',
      'delete': 'حذف',
      'edit': 'تعديل',
      'save': 'حفظ',
      'cancel': 'إلغاء',
      'yes': 'نعم',
      'no': 'لا',
      'loading': 'جاري التحميل...',
      'error': 'خطأ',
      'success': 'نجح',
      'todayJobs': 'الوظائف اليوم',
      'relevantJobs': 'الوظائف ذات الصلة',
      'monitoredGroups': 'المجموعات المراقبة',
      'totalKeywords': 'إجمالي الكلمات المفتاحية',
      'monitoringStatus': 'حالة المراقبة',
      'lastSync': 'آخر مزامنة',
      'company': 'الشركة',
      'title': 'المسمى الوظيفي',
      'location': 'الموقع',
      'date': 'التاريخ',
      'source': 'المصدر',
      'importance': 'الأهمية',
      'share': 'مشاركة',
      'addFavorite': 'إضافة إلى المفضلة',
      'removeFavorite': 'إزالة من المفضلة',
      'darkMode': 'الوضع الليلي',
      'language': 'اللغة',
      'notifications': 'الإشعارات',
      'backgroundMonitoring': 'المراقبة في الخلفية',
      'autoUpdate': 'التحديث التلقائي',
      'exportDatabase': 'تصدير قاعدة البيانات',
      'importDatabase': 'استيراد قاعدة البيانات',
      'backup': 'نسخة احتياطية',
      'restore': 'استعادة',
      'logout': 'تسجيل الخروج',
      'login': 'تسجيل الدخول',
      'connecting': 'جاري الاتصال بـ Telegram...',
      'enterPhoneNumber': 'أدخل رقم هاتفك',
      'enterCode': 'أدخل رمز التحقق',
      'enterPassword': 'أدخل كلمة المرور',
    },
  };

  static String translate(String key, String languageCode) {
    return _localizedStrings[languageCode]?[key] ?? _localizedStrings['en']![key]!;
  }
}
